### ISSUE TITLE
缩放取消问题，贴图和文字会变小。

### ISSUE THREAD

**Issue by liuguangxu1988** [vachelx/PictureEditor#1]
1 先贴emoji或文本,放大数倍；
2 选择裁剪，放大底图数倍后取消；
3 返回后底图正常，但emoji和文本变得非常小，期待不应改缩小。

原因为底图放大的时候，贴图已经到达了最大的放大倍数，不会随底图继续放大，取消时又缩小了底图放大的倍数。
期待有优雅的解决方案。

**Comment by vachelx** [comment]
贴图和文本的最大缩放倍数未考虑父控件的当前缩放倍数，已修复
